.pragma library

// Tahoe symbol name registry (T13). Maps semantic names and legacy Material
// codepoint strings to PNG filenames under assets/icons/symbols/.
// Generated from Material Icons Round glyphs pre-rendered as white @2x PNGs.

var CodepointToName = {
    "\ue001": "error",
    "\ue002": "error-outline",
    "\ue029": "play",
    "\ue034": "skip-next",
    "\ue037": "skip-previous",
    "\ue042": "volume-down",
    "\ue044": "volume-mute-icon",
    "\ue045": "volume-off",
    "\ue04d": "volume-up",
    "\ue04f": "volume-mute",
    "\ue050": "volume",
    "\ue0c8": "place",
    "\ue145": "add",
    "\ue14b": "clear",
    "\ue14c": "cut",
    "\ue14d": "copy",
    "\ue14f": "clipboard",
    "\ue15b": "remove",
    "\ue161": "save",
    "\ue195": "storage",
    "\ue19c": "sd",
    "\ue1a3": "devices",
    "\ue1a4": "device-hub",
    "\ue1a5": "brightness-auto",
    "\ue1a7": "bluetooth",
    "\ue1ad": "bluetooth-searching",
    "\ue1b1": "thermostat",
    "\ue1bd": "ethernet",
    "\ue1db": "battery-full",
    "\ue256": "remove-circle",
    "\ue25f": "add-circle",
    "\ue2bd": "cloud",
    "\ue2c2": "folder",
    "\ue2c4": "folder-open",
    "\ue2c7": "folder-shared",
    "\ue30d": "phone",
    "\ue312": "keyboard",
    "\ue313": "laptop",
    "\ue322": "speaker",
    "\ue323": "tablet",
    "\ue332": "fan",
    "\ue333": "display",
    "\ue338": "watch",
    "\ue3a3": "sunny",
    "\ue3a4": "incandescent",
    "\ue3a9": "brightness-2",
    "\ue3aa": "brightness-3",
    "\ue3b0": "brightness-5",
    "\ue3b7": "brightness-7",
    "\ue3c9": "color-lens",
    "\ue3ea": "filter",
    "\ue3f4": "image",
    "\ue405": "camera",
    "\ue40b": "photo",
    "\ue425": "timelapse",
    "\ue42d": "timer",
    "\ue430": "tonality",
    "\ue518": "brightness",
    "\ue51c": "sleep",
    "\ue539": "flight",
    "\ue53b": "airport",
    "\ue55c": "my-location",
    "\ue55e": "explore",
    "\ue55f": "location",
    "\ue5c3": "apps",
    "\ue5c4": "arrow-back",
    "\ue5c9": "cancel",
    "\ue5ca": "check",
    "\ue5cb": "chevron-left",
    "\ue5cc": "chevron-right",
    "\ue5cd": "close",
    "\ue5ce": "expand-less",
    "\ue5cf": "expand-more",
    "\ue5d2": "menu",
    "\ue5d5": "refresh",
    "\ue5d8": "arrow-up",
    "\ue5db": "arrow-down",
    "\ue63c": "signal",
    "\ue63e": "wifi",
    "\ue798": "ac",
    "\ue7c9": "priority",
    "\ue7f1": "city",
    "\ue7f4": "notifications",
    "\ue7f6": "notifications-off",
    "\ue7fd": "person",
    "\ue7fe": "person-add",
    "\ue80b": "public",
    "\ue80d": "school",
    "\ue80f": "share",
    "\ue818": "stars",
    "\ue81a": "whatshot",
    "\ue835": "radio-off",
    "\ue84e": "bookmark",
    "\ue859": "schedule",
    "\ue863": "visibility",
    "\ue866": "check-circle",
    "\ue868": "delete-fill",
    "\ue869": "done",
    "\ue86a": "info",
    "\ue86c": "done-all",
    "\ue86f": "code",
    "\ue871": "dashboard",
    "\ue872": "delete",
    "\ue873": "description",
    "\ue876": "check-done",
    "\ue87d": "favorite",
    "\ue88a": "home",
    "\ue88e": "info-e88e",
    "\ue88f": "help-circle",
    "\ue897": "lock",
    "\ue89e": "open",
    "\ue8a0": "language",
    "\ue8a7": "windows",
    "\ue8ac": "power",
    "\ue8ad": "print",
    "\ue8b2": "battery",
    "\ue8b5": "search-off",
    "\ue8b6": "search",
    "\ue8b8": "settings",
    "\ue8c1": "cart",
    "\ue8c4": "notes",
    "\ue8d0": "windows-list",
    "\ue8d1": "view-module",
    "\ue8d2": "view-quilt",
    "\ue8d3": "view-stream",
    "\ue8d4": "workspace",
    "\ue8e5": "performance",
    "\ue8e8": "dns",
    "\ue8ef": "extension",
    "\ue8f4": "fingerprint",
    "\ue8f5": "flight-takeoff",
    "\ue8f9": "gavel",
    "\ue8ff": "help",
    "\ue915": "event",
    "\ue91f": "bug",
    "\ue97a": "memory",
    "\ue9ba": "logout",
    "\ue9e4": "bolt",
    "\ue9e9": "touch",
    "\ue9ef": "tag",
    "\uea35": "eco",
    "\uea46": "biotech",
    "\uea5f": "science",
    "\uea77": "psychology",
    "\ueb37": "dark-mode",
    "\ueb3b": "light-mode",
    "\ueb81": "sensors",
    "\ueb8e": "water",
    "\uebdb": "air",
    "\uef6b": "password",
    "\uefd8": "chart",
    "\uf090": "download",
    "\uf09b": "upload",
    "\uf1ad": "umbrella",
    "\uf20c": "leaderboard",
};

var NameToFile = {
    "error": "error.png",
    "error-outline": "error-outline.png",
    "play": "play.png",
    "skip-next": "skip-next.png",
    "skip-previous": "skip-previous.png",
    "volume-down": "volume-down.png",
    "volume-mute-icon": "volume-mute-icon.png",
    "volume-off": "volume-off.png",
    "volume-up": "volume-up.png",
    "volume-mute": "volume-mute.png",
    "volume": "volume.png",
    "place": "place.png",
    "add": "add.png",
    "clear": "clear.png",
    "cut": "cut.png",
    "copy": "copy.png",
    "clipboard": "clipboard.png",
    "remove": "remove.png",
    "save": "save.png",
    "storage": "storage.png",
    "sd": "sd.png",
    "devices": "devices.png",
    "device-hub": "device-hub.png",
    "brightness-auto": "brightness-auto.png",
    "bluetooth": "bluetooth.png",
    "bluetooth-searching": "bluetooth-searching.png",
    "thermostat": "thermostat.png",
    "ethernet": "ethernet.png",
    "battery-full": "battery-full.png",
    "remove-circle": "remove-circle.png",
    "add-circle": "add-circle.png",
    "cloud": "cloud.png",
    "folder": "folder.png",
    "folder-open": "folder-open.png",
    "folder-shared": "folder-shared.png",
    "phone": "phone.png",
    "keyboard": "keyboard.png",
    "laptop": "laptop.png",
    "speaker": "speaker.png",
    "tablet": "tablet.png",
    "fan": "fan.png",
    "display": "display.png",
    "watch": "watch.png",
    "sunny": "sunny.png",
    "incandescent": "incandescent.png",
    "brightness-2": "brightness-2.png",
    "brightness-3": "brightness-3.png",
    "brightness-5": "brightness-5.png",
    "brightness-7": "brightness-7.png",
    "color-lens": "color-lens.png",
    "filter": "filter.png",
    "image": "image.png",
    "camera": "camera.png",
    "photo": "photo.png",
    "timelapse": "timelapse.png",
    "timer": "timer.png",
    "tonality": "tonality.png",
    "brightness": "brightness.png",
    "sleep": "sleep.png",
    "flight": "flight.png",
    "airport": "airport.png",
    "my-location": "my-location.png",
    "explore": "explore.png",
    "location": "location.png",
    "apps": "apps.png",
    "arrow-back": "arrow-back.png",
    "cancel": "cancel.png",
    "check": "check.png",
    "chevron-left": "chevron-left.png",
    "chevron-right": "chevron-right.png",
    "close": "close.png",
    "expand-less": "expand-less.png",
    "expand-more": "expand-more.png",
    "menu": "menu.png",
    "refresh": "refresh.png",
    "arrow-up": "arrow-up.png",
    "arrow-down": "arrow-down.png",
    "signal": "signal.png",
    "wifi": "wifi.png",
    "ac": "ac.png",
    "priority": "priority.png",
    "city": "city.png",
    "notifications": "notifications.png",
    "notifications-off": "notifications-off.png",
    "person": "person.png",
    "person-add": "person-add.png",
    "public": "public.png",
    "school": "school.png",
    "share": "share.png",
    "stars": "stars.png",
    "whatshot": "whatshot.png",
    "radio-off": "radio-off.png",
    "bookmark": "bookmark.png",
    "schedule": "schedule.png",
    "visibility": "visibility.png",
    "check-circle": "check-circle.png",
    "delete-fill": "delete-fill.png",
    "done": "done.png",
    "info": "info.png",
    "done-all": "done-all.png",
    "code": "code.png",
    "dashboard": "dashboard.png",
    "delete": "delete.png",
    "description": "description.png",
    "check-done": "check-done.png",
    "favorite": "favorite.png",
    "home": "home.png",
    "info-e88e": "info-e88e.png",
    "help-circle": "help-circle.png",
    "lock": "lock.png",
    "open": "open.png",
    "language": "language.png",
    "windows": "windows.png",
    "power": "power.png",
    "print": "print.png",
    "battery": "battery.png",
    "search-off": "search-off.png",
    "search": "search.png",
    "settings": "settings.png",
    "cart": "cart.png",
    "notes": "notes.png",
    "windows-list": "windows-list.png",
    "view-module": "view-module.png",
    "view-quilt": "view-quilt.png",
    "view-stream": "view-stream.png",
    "workspace": "workspace.png",
    "performance": "performance.png",
    "dns": "dns.png",
    "extension": "extension.png",
    "fingerprint": "fingerprint.png",
    "flight-takeoff": "flight-takeoff.png",
    "gavel": "gavel.png",
    "help": "help.png",
    "event": "event.png",
    "bug": "bug.png",
    "memory": "memory.png",
    "logout": "logout.png",
    "bolt": "bolt.png",
    "touch": "touch.png",
    "tag": "tag.png",
    "eco": "eco.png",
    "biotech": "biotech.png",
    "science": "science.png",
    "psychology": "psychology.png",
    "dark-mode": "dark-mode.png",
    "light-mode": "light-mode.png",
    "sensors": "sensors.png",
    "water": "water.png",
    "air": "air.png",
    "password": "password.png",
    "chart": "chart.png",
    "download": "download.png",
    "upload": "upload.png",
    "umbrella": "umbrella.png",
    "leaderboard": "leaderboard.png",
    "AppStore-Symbol": "AppStore-Symbol.png",
    "Back-Symbol": "Back-Symbol.png",
    "Copy-Symbol": "Copy-Symbol.png",
    "Folder-Symbol": "Folder-Symbol.png",
    "Forward-Symbol": "Forward-Symbol.png",
    "Shortcuts-Symbol": "Shortcuts-Symbol.png",
    "appstore": "AppStore-Symbol.png",
    "back": "Back-Symbol.png",
    "copy-symbol": "Copy-Symbol.png",
    "folder-symbol": "Folder-Symbol.png",
    "forward": "Forward-Symbol.png",
    "shortcuts": "Shortcuts-Symbol.png",
};

function normalizeKey(value) {
    return String(value || "").trim();
}

function nameFromCodepoint(code) {
    var key = normalizeKey(code);
    if (key.length === 0)
        return "";
    if (Object.prototype.hasOwnProperty.call(CodepointToName, key))
        return CodepointToName[key];
    return "";
}

function resolveName(value) {
    var key = normalizeKey(value);
    if (key.length === 0)
        return "";
    // Already a semantic name?
    if (Object.prototype.hasOwnProperty.call(NameToFile, key))
        return key;
    // Bare filename
    if (key.indexOf(".png") > 0) {
        var bare = key.replace(/\.png$/, "");
        if (Object.prototype.hasOwnProperty.call(NameToFile, bare))
            return bare;
        return bare;
    }
    // Legacy Material codepoint string (single private-use char)
    var fromCp = nameFromCodepoint(key);
    if (fromCp.length > 0)
        return fromCp;
    // hyphen/underscore normalize
    var alt = key.replace(/_/g, "-");
    if (Object.prototype.hasOwnProperty.call(NameToFile, alt))
        return alt;
    return key;
}

function fileName(value) {
    var name = resolveName(value);
    if (name.length === 0)
        return "";
    if (Object.prototype.hasOwnProperty.call(NameToFile, name))
        return NameToFile[name];
    if (name.indexOf(".png") > 0)
        return name;
    return name + ".png";
}

function isKnown(value) {
    var name = resolveName(value);
    return name.length > 0 && Object.prototype.hasOwnProperty.call(NameToFile, name);
}
